### ISSUE TITLE
Uploaded the entire minecraft source code

### ISSUE THREAD

**Issue by 0x3C50** [Utility-Client/UtilityClient2#45]
Since uploading the minecraft source code to any website (per license) is illegal, i recommend you gitignore net/minecraft, or mojang might send a dmca your way.

**Comment by GamingCrafthd** [comment]
It wasn't by accident. UC2 modifies parts of the source code of Minecraft.
I'll planned to remove the source code soon anyways.

**Comment by GamingCrafthd** [comment]
**Removed source code with [this commit](https://github.com/Utility-Client/UtilityClient2/commit/fef71cda6fa1b46ea093386f9d20070f3efeebe8).**

Thank you for creating a issue.
